### ISSUE TITLE
Change the parameters of the init_data and init_bss functions to immutable constants

### ISSUE THREAD

**Issue by acuster** [rust-embedded/r0#7]
The methods init_bss(.) and init_data(.) should treat their parameters as immutable constants, since semantically that is what they are and because it would lead to a cleaner API.

The documentation around line 35 of lib.rs, explains the usage of this crate requires another block of code to pull in the linker script addresses as external values, e.g.
```
static mut _sbss: u32;
```
Semantically, this symbol refers to the start of the .bss code segment (aka 'output section'). It makes no semantic sense for this to be mutable. As I understand it, the mutability of these variables is merely to allow us to reuse them directly in code. Implementation is leaking into API.

If that is the only reason, it seems like a poor tradeoff: 
(1) we add mutability throughout the API when we don't actually need it
(2) we violate the semantics of the name of the variable ('start of the bss segment')
It would be better to make a mutable variable inside the method and copy the constant value to that temporary variable, then use that. Something like, for line 131:
```
   let mut src: u32 = sdata;
   let mut dest: u32 = sidata;

    while src < edata {
        ptr::write(src, ptr::read(dest));
        src = src.offset(1);
        dest = dest.offset(1);
    }
```
then all the linker variables could be treated as constants in the API. 

cheers,
  ~adrian

**Comment by pftbest** [comment]
I'm sorry, but it shouldn't make any difference whether `sdata` and `sidata` parameters are mutable or not, because it's not part of the API. If you take a [look at documentation](https://docs.rs/r0/0.2.2/r0/fn.init_data.html) you can see that it doesn't even show the `mut` keyword for this parameters, because it doesn't affect the usage in any meaningful way.

> As I understand it, the mutability of these variables is merely to allow us to reuse them directly in code.

No it's not. I believe you are confusing mutability of function arguments with mutability of the raw pointers for the memory they are pointing to. Semantically `static mut _sbss: u32;` is not a 32bit integer, it's only a special symbol. We must not read (or write) any value out of `_sbss`, we can only take its address (pointer to `_sbss`) and use it as a physical address of the memory section that we care about, in this case `.bss`. `u32` here is just to set correct alignment, the actual `u32` doesn't exist. And we need a `*mut` pointer here because we intend to write zeroes to that memory location, so `_sbss` needs to be mut, to allow us take this reference `&mut _sbss` and cast it to `*mut u32`

**Comment by japaric** [comment]
Like @pftbest said the `mut` in the parameter binding doesn't affect the signature of the function. The `mut` binding is just sugar as seen below:

``` rust
fn foo(x: i32) {
    let mut x = x;
    // ..
}

// sugared version of `foo`
fn bar(mut x: i32) {
    // ..
}
```

Mutations done on the `x` variable won't affect the actual argument passed to `foo` or `bar` because it's a copy (`memcpy`) of the argument the function was called with.

``` rust
let x = 0;
foo(x);
// x will always be `0` here
bar(x);
// x will always be `0` here
```

Hope that makes sense!

I'm going to close this issue as changing the binding have no effect on the semantics of the API. It would probably make the implementation a little more verbose though so best to keep the implementation as it is.
